<footer>
        <a href="index.html"><img src="images/web_weavers_logo_only_pic.jpg" alt="Purple spiderweb from Web Weavers logo"></a>
        <p>&copy;&nbsp;2025 Web Weavers</p>
        <p>Email: <a href="mailto:info@webweavers.edu.au">info@webweavers.edu.au</a></p>
        <p>Link:
            <a href="https://tyler105919952.atlassian.net/jira/software/projects/WW/summary" target="_blank">
                Web Weavers Jira Project
            </a>
        </p>
        <p>Link:
          <a href="https://github.com/102347055/webweavers-project-part1" target="_blank">
              Web Weavers Github Repository
          </a>
      </p>
    </footer>