<header>
    <nav>
      <a href="index.html"><img src="images/web_weavers_logo.jpg" id = "home_logo"    
        alt="Dark purple spiderweb against a lighter purple background with text reading 'Web Weavers'" 
        title="Web Weavers Company Logo"></a>   <!-- Company logo created on Canva-->
      <ul class="navbar">
        <li class="page-links"><a href="jobs.html">Current Opportunities</a></li>
        <li class="page-links"><a href="apply.html">Apply Now</a></li> 
        <li class="page-links"><a href="about.html">About Us</a></li> 
      </ul>
      <ul class="nav_buttons">
        <li><a href="manage.php">Log In</a></li>
        <li><a href="enhancements.php">Get Started</a></li>
      </ul>
    </nav>
  </header>