<header>
    <nav>
      <a href="index.php"><img src="images/web_weavers_logo.jpg" id = "home_logo"    
        alt="Dark purple spiderweb against a lighter purple background with text reading 'Web Weavers'" 
        title="Web Weavers Company Logo"></a>   <!-- Company logo created on Canva-->
      <ul class="navbar">
        <li class="page-links"><a href="jobs.php">Current Opportunities</a></li>
        <li class="page-links"><a href="apply.php">Apply Now</a></li> 
        <li class="page-links"><a href="about.php">About Us</a></li> 
      </ul>
      <ul class="nav_buttons">
        <li><a href="reg.php">Get Started</a></li>
        <li><a href="login.php">Log In</a></li>
        <li><a href="logout.php">Log Out</a></li>
      </ul>
    </nav>
</header>